os:
  - linux

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

install:
  - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
  - bash ./support/texlive.sh
  - tlmgr update --self --all −−no−auto−install

script:
  - make test
  - make doc
